### ISSUE TITLE
Forced domain not retaining setting

### ISSUE THREAD

**Issue by GitPuffy** [rbeer/nodebb-plugin-smoothshorts#5]
Running nodebb-plugin-smoothshorts under NodeBB `v1.0.2` I am unable to set a "forced domain."

I click the checkbox and enter a domain name yet after clicking "Save Settings" the checkbox and my custom domain name reset back to blank.

I hope you are still actively developing this plugin as it works pretty well.  I do have a few other small issues with it but they are not as severe as this "forced domain" one.

Thanks.

**Comment by rbeer** [comment]
Hi there! :smile:
To be honest, I'm surprised that it works >1.0.0, at all. I was just coming here onto GitHub to get some inspiration for my evening project. I guess I just found it. :+1: 

Since my last update, I actually found an HTML5 API that allows us to copy into the clipboard (not read from it, luckily), so my general intention is to rewrite the plugin and maintain those modifier-key acrobatics as a fallback, only.

For now, I'll spin up `v1.0.2` and see that I get this one fixed, first. :smile:

**Comment by GitPuffy** [comment]
Great!  Let me know if you would like me to test anything.  

And since you are here I'll mention that I can only get the smoothshorts link when copying the link from the exact category it is in.  If I try to get it while copying from say the homepage, or the "recents" route, etc., it does not work.  Uh, was that even clear?

**Comment by rbeer** [comment]
Yes, I know what you mean. I already know what the problem is: The plugin checks explicitly for the category and topic views to trigger the replacement. I'll put that on the list, 'cause I just decided to refactor the ***\* out of this. Almost embarrassing what a mess I produced there. :smile: 

P.S. npm is also updated.

**Comment by GitPuffy** [comment]
This fix works great.  Thank you.
